import { Disaster } from "../types/disaster";

// ─────────────────────────────────────────────────────────────────────────────
// NOTE: These are SIMULATED events for demonstration purposes.
// Real data feeds:
//   • Earthquakes  → USGS API (free):   https://earthquake.usgs.gov/fdsnws/event/1/query
//   • Wildfires    → NASA FIRMS (free): https://firms.modaps.eosdis.nasa.gov/api/
//   • Storms/Floods→ NOAA (free):       https://www.weather.gov/documentation/services-web-api
//   • Disasters    → GDACS (free):      https://www.gdacs.org/xml/rss.xml
//   • Wars/Conflicts→ ACLED (free tier): https://acleddata.com/
// ─────────────────────────────────────────────────────────────────────────────

export const DISASTERS: Disaster[] = [
  {
    id: 1,
    type: "WILDFIRE",
    severity: "CRITICAL",
    alert: "red",
    location: "Mato Grosso, Brazil",
    lat: -12.5, lng: -55.4,
    date: "2026-03-20",
    source: "NASA FIRMS",
    isLive: true,
    primary: "Soybeans",
    primarySymbol: "ZS1!",
    primary_pct: 22,
    direction: "UP",
    magnitude: 8.4,
    confidence: 0.87,
    description: "Massive wildfire complex consuming key soybean-producing zones in Mato Grosso. 85,000 hectares burned, active spread toward harvest areas.",
    ai_models: [
      { name: "AI ALPHA", probability: 89, prediction: 8.1 },
      { name: "AI BETA",   probability: 85, prediction: 8.9 },
      { name: "AI GAMMA",    probability: 87, prediction: 8.2 },
    ],
    indirect: [
      { asset: "Corn",         impact: "+4.2%", direction: "up",   category: "commodity" },
      { asset: "BRL/USD",      impact: "-1.8%", direction: "down", category: "forex"     },
      { asset: "ADM",          impact: "+3.1%", direction: "up",   category: "equity"    },
      { asset: "Cattle",       impact: "+2.6%", direction: "up",   category: "commodity" },
      { asset: "Palm Oil",     impact: "+1.9%", direction: "up",   category: "commodity" },
    ],
        hasMarketImpact: true,
  },
  {
    id: 2,
    type: "EARTHQUAKE",
    severity: "CRITICAL",
    alert: "red",
    location: "Atacama Region, Chile",
    lat: -27.3, lng: -70.2,
    date: "2026-03-21",
    source: "USGS",
    isLive: true,
    primary: "Copper",
    primarySymbol: "HG1!",
    primary_pct: 28,
    direction: "UP",
    magnitude: 11.2,
    confidence: 0.91,
    description: "M6.8 earthquake near critical copper mining infrastructure in Atacama Desert. Major CODELCO operations suspended pending damage assessment.",
    ai_models: [
      { name: "AI ALPHA", probability: 92, prediction: 11.5 },
      { name: "AI BETA",   probability: 90, prediction: 10.8 },
      { name: "AI GAMMA",    probability: 91, prediction: 11.3 },
    ],
    indirect: [
      { asset: "Lithium",          impact: "+5.8%", direction: "up",   category: "commodity" },
      { asset: "CLP/USD",          impact: "-2.4%", direction: "down", category: "forex"     },
      { asset: "Freeport-McMoRan", impact: "+4.7%", direction: "up",   category: "equity"    },
      { asset: "Nickel",           impact: "+2.1%", direction: "up",   category: "commodity" },
      { asset: "ICLN ETF",         impact: "+1.3%", direction: "up",   category: "index"     },
    ],
        hasMarketImpact: true,
  },
  {
    id: 3,
    type: "HURRICANE",
    severity: "HIGH",
    alert: "orange",
    location: "Gulf of Mexico, Cat. 3",
    lat: 25.1, lng: -91.3,
    date: "2026-03-19",
    source: "NOAA",
    isLive: true,
    primary: "Crude Oil",
    primarySymbol: "CL1!",
    primary_pct: 18,
    direction: "UP",
    magnitude: 6.7,
    confidence: 0.83,
    description: "Category 3 hurricane tracking toward Gulf Coast oil infrastructure. 18% of US Gulf crude production capacity potentially offline within 48 hours.",
    ai_models: [
      { name: "AI ALPHA", probability: 84, prediction: 6.9 },
      { name: "AI BETA",   probability: 81, prediction: 6.4 },
      { name: "AI GAMMA",    probability: 83, prediction: 6.8 },
    ],
    indirect: [
      { asset: "Natural Gas",  impact: "+8.3%", direction: "up",   category: "energy"    },
      { asset: "XOM",          impact: "+2.9%", direction: "up",   category: "equity"    },
      { asset: "HAL",          impact: "+3.4%", direction: "up",   category: "equity"    },
      { asset: "Airlines UAL", impact: "-1.6%", direction: "down", category: "equity"    },
      { asset: "USD/MXN",      impact: "+1.1%", direction: "up",   category: "forex"     },
    ],
        hasMarketImpact: true,
  },
  {
    id: 4,
    type: "DROUGHT",
    severity: "MEDIUM",
    alert: "yellow",
    location: "Australian Wheat Belt, WA",
    lat: -31.9, lng: 117.8,
    date: "2026-03-15",
    source: "GDACS",
    isLive: false,
    primary: "Wheat",
    primarySymbol: "ZS1!",
    primary_pct: 9,
    direction: "UP",
    magnitude: 4.1,
    confidence: 0.74,
    description: "Severe drought in WA wheat belt. NDVI satellite data shows 34% vegetation health decline vs 5-year average. Harvest yield risk elevated.",
    ai_models: [
      { name: "AI ALPHA", probability: 76, prediction: 4.3 },
      { name: "AI BETA",   probability: 72, prediction: 3.9 },
      { name: "AI GAMMA",    probability: 74, prediction: 4.1 },
    ],
    indirect: [
      { asset: "Barley",         impact: "+3.2%", direction: "up",   category: "commodity" },
      { asset: "AUD/USD",        impact: "-0.9%", direction: "down", category: "forex"     },
      { asset: "Flour Futures",  impact: "+2.8%", direction: "up",   category: "commodity" },
      { asset: "Feed Costs",     impact: "+2.1%", direction: "up",   category: "commodity" },
    ],
        hasMarketImpact: true,
  },
  {
    id: 5,
    type: "FLOOD",
    severity: "HIGH",
    alert: "orange",
    location: "Yangtze River Basin, China",
    lat: 30.5, lng: 114.3,
    date: "2026-03-18",
    source: "GDACS",
    isLive: true,
    primary: "Rare Earth Metals",
    primarySymbol: "GC1!",
    primary_pct: 31,
    direction: "UP",
    magnitude: 9.8,
    confidence: 0.89,
    description: "Record flooding across Yangtze River Basin affecting rare earth processing and manufacturing hubs. 12,400 km² submerged, supply chains disrupted.",
    ai_models: [
      { name: "AI ALPHA", probability: 90, prediction: 9.4  },
      { name: "AI BETA",   probability: 88, prediction: 10.1 },
      { name: "AI GAMMA",    probability: 89, prediction: 9.9  },
    ],
    indirect: [
      { asset: "SOXX ETF",   impact: "+3.7%", direction: "up",   category: "index"     },
      { asset: "CNY/USD",    impact: "-1.2%", direction: "down", category: "forex"     },
      { asset: "Coal",       impact: "+4.1%", direction: "up",   category: "energy"    },
      { asset: "Solar ETF",  impact: "+5.2%", direction: "up",   category: "index"     },
      { asset: "AAPL",       impact: "-1.8%", direction: "down", category: "equity"    },
    ],
        hasMarketImpact: true,
  },
  {
    id: 6,
    type: "WAR",
    severity: "CRITICAL",
    alert: "red",
    location: "Black Sea / Ukraine",
    lat: 46.5, lng: 32.0,
    date: "2026-03-21",
    source: "ACLED",
    isLive: true,
    primary: "Wheat",
    primarySymbol: "ZS1!",
    primary_pct: 26,
    direction: "UP",
    magnitude: 14.2,
    confidence: 0.93,
    description: "Escalating Black Sea conflict disrupting grain export corridors. Ukraine + Russia account for 26% of global wheat exports. Port closures confirmed at Odessa.",
    ai_models: [
      { name: "AI ALPHA", probability: 95, prediction: 14.5 },
      { name: "AI BETA",   probability: 92, prediction: 13.8 },
      { name: "AI GAMMA",    probability: 94, prediction: 14.3 },
    ],
    indirect: [
      { asset: "Corn",          impact: "+6.1%", direction: "up",   category: "commodity" },
      { asset: "Natural Gas",   impact: "+9.4%", direction: "up",   category: "energy"    },
      { asset: "Gold",          impact: "+3.2%", direction: "up",   category: "commodity" },
      { asset: "EUR/USD",       impact: "-2.1%", direction: "down", category: "forex"     },
      { asset: "Defense ETF",   impact: "+7.8%", direction: "up",   category: "index"     },
      { asset: "Fertilizer",    impact: "+11.2%",direction: "up",   category: "commodity" },
    ],
        hasMarketImpact: true,
  },
  {
    id: 7,
    type: "WAR",
    severity: "HIGH",
    alert: "orange",
    location: "Strait of Hormuz, Persian Gulf",
    lat: 26.5, lng: 56.3,
    date: "2026-03-20",
    source: "ACLED",
    isLive: true,
    primary: "Crude Oil",
    primarySymbol: "CL1!",
    primary_pct: 21,
    direction: "UP",
    magnitude: 18.6,
    confidence: 0.88,
    description: "Naval skirmishes near Strait of Hormuz threatening 21% of global seaborne oil. Insurance premiums for tankers surging. Iranian naval activity elevated.",
    ai_models: [
      { name: "AI ALPHA", probability: 91, prediction: 19.2 },
      { name: "AI BETA",   probability: 87, prediction: 18.1 },
      { name: "AI GAMMA",    probability: 88, prediction: 18.5 },
    ],
    indirect: [
      { asset: "Brent Crude",   impact: "+18.6%",direction: "up",   category: "energy"    },
      { asset: "Natural Gas",   impact: "+7.3%", direction: "up",   category: "energy"    },
      { asset: "VIX",           impact: "+22.4%",direction: "up",   category: "index"     },
      { asset: "Gold",          impact: "+4.8%", direction: "up",   category: "commodity" },
      { asset: "USD/JPY",       impact: "-3.1%", direction: "down", category: "forex"     },
      { asset: "Airlines",      impact: "-8.2%", direction: "down", category: "equity"    },
    ],
        hasMarketImpact: true,
  },
];

export const ALERT_CONFIG = {
  red:    { bg: "bg-red-950/40",    border: "border-red-500/40",    text: "text-red-300",    dot: "bg-red-500",    hex: "#ef4444" },
  orange: { bg: "bg-orange-950/40", border: "border-orange-500/40", text: "text-orange-300", dot: "bg-orange-500", hex: "#f97316" },
  yellow: { bg: "bg-yellow-950/30", border: "border-yellow-500/30", text: "text-yellow-300", dot: "bg-yellow-500", hex: "#eab308" },
} as const;

export const TYPE_ICONS: Record<string, string> = {
  WILDFIRE:   "🔥",
  EARTHQUAKE: "⚡",
  HURRICANE:  "🌀",
  DROUGHT:    "☀️",
  FLOOD:      "🌊",
  WAR:        "💥",
};

export const TYPE_LABELS: Record<string, string> = {
  ALL:        "All",
  WILDFIRE:   "Fire",
  EARTHQUAKE: "Earthquake",
  HURRICANE:  "Hurricane",
  DROUGHT:    "Drought",
  FLOOD:      "Flood",
  WAR:        "War",
};

export const COMMODITY_CATEGORIES = [
  "All",
  "commodity",
  "energy",
  "equity",
  "forex",
  "index",
] as const;