import { Disaster } from "../types/disaster";

export const DISASTERS: Disaster[] = [
  {
    id: 1,
    type: "WILDFIRE",
    severity: "CRITICAL",
    alert: "red",
    location: "Mato Grosso, Brazil",
    lat: -12.5,
    lng: -55.4,
    area_ha: 85000,
    date: "2026-03-20",
    primary: "Soybeans",
    primary_pct: 22,
    direction: "UP",
    magnitude: 8.4,
    confidence: 0.87,
    indirect: [
      { asset: "Corn", impact: "+4.2%", direction: "up" },
      { asset: "BRL/USD", impact: "-1.8%", direction: "down" },
      { asset: "ADM", impact: "+3.1%", direction: "up" },
      { asset: "Cattle Futures", impact: "+2.6%", direction: "up" },
      { asset: "Palm Oil", impact: "+1.9%", direction: "up" },
    ],
    model_breakdown: { xgboost: 8.1, lightgbm: 8.9, pytorch: 8.2 },
    description:
      "Massive wildfire complex consuming key soybean-producing zones in Mato Grosso state. 85,000 hectares burned with active spread towards harvest areas.",
  },
  {
    id: 2,
    type: "EARTHQUAKE",
    severity: "CRITICAL",
    alert: "red",
    location: "Atacama Region, Chile",
    lat: -27.3,
    lng: -70.2,
    magnitude_eq: 6.8,
    depth_km: 45,
    date: "2026-03-21",
    primary: "Copper",
    primary_pct: 28,
    direction: "UP",
    magnitude: 11.2,
    confidence: 0.91,
    indirect: [
      { asset: "Lithium", impact: "+5.8%", direction: "up" },
      { asset: "CLP/USD", impact: "-2.4%", direction: "down" },
      { asset: "Freeport-McMoRan", impact: "+4.7%", direction: "up" },
      { asset: "Nickel", impact: "+2.1%", direction: "up" },
      { asset: "Renewable Energy ETF", impact: "+1.3%", direction: "up" },
    ],
    model_breakdown: { xgboost: 11.5, lightgbm: 10.8, pytorch: 11.3 },
    description:
      "M6.8 earthquake near critical copper mining infrastructure in Atacama Desert. Major CODELCO operations have suspended as damage assessment is underway.",
  },
  {
    id: 3,
    type: "HURRICANE",
    severity: "HIGH",
    alert: "orange",
    location: "Gulf of Mexico, Category 3",
    lat: 25.1,
    lng: -91.3,
    wind_speed_kmh: 195,
    date: "2026-03-19",
    primary: "Crude Oil",
    primary_pct: 18,
    direction: "UP",
    magnitude: 6.7,
    confidence: 0.83,
    indirect: [
      { asset: "Natural Gas", impact: "+8.3%", direction: "up" },
      { asset: "XOM", impact: "+2.9%", direction: "up" },
      { asset: "HAL", impact: "+3.4%", direction: "up" },
      { asset: "Airlines (UAL)", impact: "-1.6%", direction: "down" },
      { asset: "USD/MXN", impact: "+1.1%", direction: "up" },
    ],
    model_breakdown: { xgboost: 6.9, lightgbm: 6.4, pytorch: 6.8 },
    description:
      "Category 3 hurricane tracking toward Gulf Coast oil infrastructure. 18% of US Gulf crude production capacity potentially offline within 48 hours.",
  },
  {
    id: 4,
    type: "DROUGHT",
    severity: "MEDIUM",
    alert: "yellow",
    location: "Australian Wheat Belt, WA",
    lat: -31.9,
    lng: 117.8,
    ndvi_drop_pct: 34,
    date: "2026-03-15",
    primary: "Wheat",
    primary_pct: 9,
    direction: "UP",
    magnitude: 4.1,
    confidence: 0.74,
    indirect: [
      { asset: "Flour Producers", impact: "+2.8%", direction: "up" },
      { asset: "AUD/USD", impact: "-0.9%", direction: "down" },
      { asset: "Barley", impact: "+3.2%", direction: "up" },
      { asset: "Feed Costs", impact: "+2.1%", direction: "up" },
    ],
    model_breakdown: { xgboost: 4.3, lightgbm: 3.9, pytorch: 4.1 },
    description:
      "Severe drought conditions in Western Australia's primary wheat belt. NDVI satellite data shows 34% vegetation health decline vs 5-year average.",
  },
  {
    id: 5,
    type: "FLOOD",
    severity: "HIGH",
    alert: "orange",
    location: "Yangtze River Basin, China",
    lat: 30.5,
    lng: 114.3,
    affected_km2: 12400,
    date: "2026-03-18",
    primary: "Rare Earth Metals",
    primary_pct: 31,
    direction: "UP",
    magnitude: 9.8,
    confidence: 0.89,
    indirect: [
      { asset: "Semiconductors (SOXX)", impact: "+3.7%", direction: "up" },
      { asset: "CNY/USD", impact: "-1.2%", direction: "down" },
      { asset: "Coal", impact: "+4.1%", direction: "up" },
      { asset: "Solar Panels", impact: "+5.2%", direction: "up" },
      { asset: "Apple Inc.", impact: "-1.8%", direction: "down" },
    ],
    model_breakdown: { xgboost: 9.4, lightgbm: 10.1, pytorch: 9.9 },
    description:
      "Record flooding across Yangtze River Basin affecting rare earth processing facilities and manufacturing hubs. 12,400 km² submerged.",
  },
];

export const ALERT_CONFIG = {
  red: {
    bg: "bg-red-950/40",
    border: "border-red-500/40",
    text: "text-red-300",
    dot: "bg-red-500",
    glow: "shadow-red-500/20",
    hex: "#ef4444",
  },
  orange: {
    bg: "bg-orange-950/40",
    border: "border-orange-500/40",
    text: "text-orange-300",
    dot: "bg-orange-500",
    glow: "shadow-orange-500/20",
    hex: "#f97316",
  },
  yellow: {
    bg: "bg-yellow-950/30",
    border: "border-yellow-500/30",
    text: "text-yellow-300",
    dot: "bg-yellow-500",
    glow: "shadow-yellow-500/20",
    hex: "#eab308",
  },
} as const;

export const TYPE_ICONS: Record<string, string> = {
  WILDFIRE: "🔥",
  EARTHQUAKE: "⚡",
  HURRICANE: "🌀",
  DROUGHT: "☀️",
  FLOOD: "🌊",
};