name: CFTC Data Job

on:
  schedule:
    - cron: "0 0 * * 0"  # Run every Sunday at 12 AM UTC (minute hour day month weekday)
  workflow_dispatch:     # Allows manual runs too

jobs:
  run-cftc-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CFTC script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python cftc_function.py